/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { RPSGameV2 } from "../RPSGameV2";

export class RPSGameV2__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<RPSGameV2> {
    return super.deploy(overrides || {}) as Promise<RPSGameV2>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): RPSGameV2 {
    return super.attach(address) as RPSGameV2;
  }
  connect(signer: Signer): RPSGameV2__factory {
    return super.connect(signer) as RPSGameV2__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): RPSGameV2 {
    return new Contract(address, _abi, signerOrProvider) as RPSGameV2;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "moves",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum RPSGameV2.Move",
        name: "_move",
        type: "uint8",
      },
      {
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
    ],
    name: "revealMove",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "revealMoveStart",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_moveHash",
        type: "bytes32",
      },
    ],
    name: "submitMove",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "submitMoveStart",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610277806100206000396000f3fe608060405234801561001057600080fd5b50600436106100575760003560e01c80632932a4c81461005c578063349283ad146100715780638d75746c1461008f578063a8f7d44214610097578063e15a808b146100aa575b600080fd5b61006f61006a366004610189565b6100bd565b005b6100796100d3565b6040516100869190610201565b60405180910390f35b6100796100d9565b61006f6100a53660046101a1565b6100df565b6100796100b836600461015b565b610149565b3360009081526006602052604090205542600755565b60085481565b60075481565b600082826040516020016100f49291906101cf565b60408051601f198184030181529181528151602092830120336000908152600690935291205490915081146101445760405162461bcd60e51b815260040161013b9061020a565b60405180910390fd5b505050565b60066020526000908152604090205481565b60006020828403121561016c578081fd5b81356001600160a01b0381168114610182578182fd5b9392505050565b60006020828403121561019a578081fd5b5035919050565b600080604083850312156101b3578081fd5b8235600481106101c1578182fd5b946020939093013593505050565b6000600484106101ed57634e487b7160e01b81526021600452602481fd5b5060f89290921b8252600182015260210190565b90815260200190565b6020808252601f908201527f506c6561736520636865636b20796f7572206d6f766520616e642073616c740060408201526060019056fea26469706673582212201c3c8e86f189e999fb45e9c3710bd2e06c190f7c51cb4ea09f44c83334b16cf164736f6c63430008000033";
